server:
  port: 8888
spring:
  application:
    name: hello-spring-cloud-config
  boot:
    admin:
      client:
        url: http://localhost:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/theGifs/mytest
          search-paths: repos
          username:
          password:
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   #是否显示IP