spring:
  application:
    name: hello-spring-cloud-service-admin      #服务提供者的名称
    #需要指明 spring.application.name，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个 name
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    #Eureka服务注册中心的地址
